spring.application.name=blogapi
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ecom_db
spring.datasource.username=kuldeep
spring.datasource.password=Jun@2026
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
logging.level.org.springframework=DEBUG
spring.devtools.restart.enabled=false